In [1]:
import pandas as pd

In [2]:
###Reading the csv file
bad_products = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample bad/Products.csv")

In [3]:
bad_products.columns

Index(['product_id ', 'product_name ', 'product_category ', 'unit_price ',
       'reorder_level ', 'lead_time_days '],
      dtype='object')

In [4]:
###Cleaning rows with end white space
bad_products.columns = bad_products.columns.str.strip()

In [5]:
bad_products.columns

Index(['product_id', 'product_name', 'product_category', 'unit_price',
       'reorder_level', 'lead_time_days'],
      dtype='object')

In [6]:
###checking duplicates
bad_products[bad_products['product_id'].duplicated(keep = False)]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
8,P009,3Broom stick,Household,850.0,10.0,0.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0
10,P009,3Broom stick,Household,850.0,10.0,0.0
11,P009,3Broom stick,Household,850.0,10.0,0.0
12,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
###Missing product ID's
bad_products[bad_products['product_id'].isnull()]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0
12,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
###Null values in Products name
bad_products[bad_products['product_name'].isnull()]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
12,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
###To check if all rows are NULL
bad_products.isnull().all(axis = 1).sum()

np.int64(1)

In [10]:
###to drop a Row with all null values in a table
bad_products = bad_products.dropna(how="all")

In [11]:
###To check if all rows are NULL
bad_products.isnull().all(axis = 1).sum()

np.int64(0)

In [12]:
###checking duplicates
bad_products[bad_products['product_id'].duplicated(keep = False)]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
8,P009,3Broom stick,Household,850.0,10.0,0.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0
10,P009,3Broom stick,Household,850.0,10.0,0.0
11,P009,3Broom stick,Household,850.0,10.0,0.0

In [13]:
###check for exact duplicates
bad_products[bad_products['product_id']=="P009"].duplicated()

8     False
10     True
11     True
dtype: bool

In [14]:
###Drop duplicates
bad_products = bad_products.drop_duplicates()

In [15]:
###checking duplicates
bad_products[bad_products['product_id'].duplicated(keep = False)]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0

In [16]:
###check for exact duplicates
bad_products[bad_products['product_id']=="P009"].duplicated()

8    False
dtype: bool

In [17]:
bad_products.isnull().sum()

product_id          2
product_name        0
product_category    0
unit_price          0
reorder_level       0
lead_time_days      0
dtype: int64

In [18]:
bad_products[bad_products["product_id"] == "P009"]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
8,P009,3Broom stick,Household,850.0,10.0,0.0

In [19]:
bad_products[bad_products["product_id"] == "P009"].duplicated()

8    False
dtype: bool

In [20]:
bad_products

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
0,P001,USB cable,Electronics,666.0,30.0,4.0
1,P002,Headphones,Electronics,932.0,25.0,6.0
2,P003,Mouse,Electronics,0.0,20.0,7.0
3,P004,Rice 10Kg,Grocery,579.0,28.0,3.0
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
5,P006,Wheat flour 500gm,Grocery,38.0,40.0,2.0
6,P007,Bucket combo,Household,486.0,20.0,4.0
7,P008,Home Cleaner,Household,520.0,15.0,3.0
8,P009,3Broom stick,Household,850.0,10.0,0.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0
13,P013,Wheat flour 500gm,Grocery,38.0,40.0,2.0

In [21]:
bad_products[bad_products["unit_price"] < 0]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0

In [22]:
###separate invalid record
invalid_record = bad_products[bad_products["unit_price"] < 0]

In [23]:
invalid_record

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0

In [24]:
bad_products[bad_products["product_id"].isnull()][["product_id","product_name","unit_price"]]

  product_id   product_name  unit_price
4        NaN    Sugar 500gm       -36.0
9        NaN  Snickers 50gm       -45.0

In [25]:
bad_products.isnull().sum()

product_id          2
product_name        0
product_category    0
unit_price          0
reorder_level       0
lead_time_days      0
dtype: int64

In [26]:
bad_products[bad_products["reorder_level"] < 0]

Empty DataFrame
Columns: [product_id, product_name, product_category, unit_price, reorder_level, lead_time_days]
Index: []

In [27]:
bad_products[bad_products["lead_time_days"] < 0]

Empty DataFrame
Columns: [product_id, product_name, product_category, unit_price, reorder_level, lead_time_days]
Index: []

In [28]:
bad_products.dtypes

product_id           object
product_name         object
product_category     object
unit_price          float64
reorder_level       float64
lead_time_days      float64
dtype: object

In [29]:
###Reading the csv file
bad_sales = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample bad/Sales.csv")

In [30]:
bad_sales.head()

  sale_id  product_id            sale_date   quantity_sold
0     S001        P005  2026-09-05 17:32:15               1
1     S002        P005  2026-09-05 17:40:09               2
2     S003        P003  2026-09-05 17:53:48               1
3     S004        P004  2026-09-05 18:12:06               1
4     S005        P001  2026-09-05 18:40:03               1

In [31]:
bad_sales.columns

Index(['sale_id ', 'product_id ', 'sale_date ', 'quantity_sold '], dtype='object')

In [32]:
bad_sales.columns = bad_sales.columns.str.strip()

In [33]:
bad_sales.columns

Index(['sale_id', 'product_id', 'sale_date', 'quantity_sold'], dtype='object')

In [34]:
bad_sales.isnull().sum()

sale_id          0
product_id       0
sale_date        0
quantity_sold    0
dtype: int64

In [35]:
bad_sales.duplicated().sum()

np.int64(0)

In [36]:
bad_sales["sale_id"].isnull().sum()

np.int64(0)

In [37]:
bad_sales["sale_id"].duplicated().sum()

np.int64(0)

In [38]:
bad_sales[~bad_sales["product_id"].isin(bad_products["product_id"])]

   sale_id product_id            sale_date  quantity_sold
0     S001       P005  2026-09-05 17:32:15              1
1     S002       P005  2026-09-05 17:40:09              2
17    S018       P010  2026-09-07 22:40:09              4
22    S023       P010  2026-09-08 23:51:01              2
24    S025       P010  2026-09-09 10:53:48              3
27    S028       P005  2026-09-09 11:48:27              2

In [39]:
bad_products[bad_products["product_id"].isin(["P005","P010"])]

Empty DataFrame
Columns: [product_id, product_name, product_category, unit_price, reorder_level, lead_time_days]
Index: []

In [40]:
invalid_sales = bad_sales[~bad_sales["product_id"].isin(bad_products["product_id"])]

In [41]:
invalid_sales

   sale_id product_id            sale_date  quantity_sold
0     S001       P005  2026-09-05 17:32:15              1
1     S002       P005  2026-09-05 17:40:09              2
17    S018       P010  2026-09-07 22:40:09              4
22    S023       P010  2026-09-08 23:51:01              2
24    S025       P010  2026-09-09 10:53:48              3
27    S028       P005  2026-09-09 11:48:27              2

In [42]:
bad_sales["sale_date"] = pd.to_datetime(bad_sales["sale_date"],errors="coerce")

In [43]:
invalid_sale_dates = bad_sales[bad_sales["sale_date"].isnull()]

In [44]:
invalid_sale_dates

Empty DataFrame
Columns: [sale_id, product_id, sale_date, quantity_sold]
Index: []

In [45]:
bad_sales[bad_sales["quantity_sold"] <= 0]

Empty DataFrame
Columns: [sale_id, product_id, sale_date, quantity_sold]
Index: []

In [46]:
bad_inventorys = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample bad/Inventory.csv")

In [47]:
bad_inventorys.head()

  product_id   current_stock
0        P001              12
1        P002              15
2        P003              10
3        P004              17
4        P005               4

In [48]:
bad_inventorys.columns

Index(['product_id ', 'current_stock '], dtype='object')

In [49]:
bad_inventorys.columns = bad_inventorys.columns.str.strip()

In [50]:
bad_inventorys.columns

Index(['product_id', 'current_stock'], dtype='object')

In [51]:
bad_inventorys.isnull().sum()

product_id       0
current_stock    0
dtype: int64

In [52]:
bad_inventorys.duplicated().sum()

np.int64(0)

In [53]:
bad_inventorys["product_id"].duplicated().sum()

np.int64(0)

In [54]:
bad_inventorys[~bad_inventorys["product_id"].isin(bad_products["product_id"])]

  product_id  current_stock
4       P005              4
9       P010              1

In [55]:
invalid_inventory = bad_inventorys[~bad_inventorys["product_id"].isin(bad_products["product_id"])]

In [56]:
invalid_inventory

  product_id  current_stock
4       P005              4
9       P010              1

In [57]:
bad_inventorys[bad_inventorys["current_stock"]<0 ]

Empty DataFrame
Columns: [product_id, current_stock]
Index: []

In [58]:
invalid_products = bad_products[
    bad_products["product_id"].isna() |
    (bad_products["unit_price"] < 0)
]

In [59]:
clean_products = bad_products.drop(invalid_products.index)

In [60]:
invalid_products

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0

In [61]:
clean_products

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
0,P001,USB cable,Electronics,666.0,30.0,4.0
1,P002,Headphones,Electronics,932.0,25.0,6.0
2,P003,Mouse,Electronics,0.0,20.0,7.0
3,P004,Rice 10Kg,Grocery,579.0,28.0,3.0
5,P006,Wheat flour 500gm,Grocery,38.0,40.0,2.0
6,P007,Bucket combo,Household,486.0,20.0,4.0
7,P008,Home Cleaner,Household,520.0,15.0,3.0
8,P009,3Broom stick,Household,850.0,10.0,0.0
13,P013,Wheat flour 500gm,Grocery,38.0,40.0,2.0

In [62]:
clean_sales = bad_sales.drop(invalid_sales.index)

In [63]:
clean_inventory = bad_inventorys.drop(invalid_inventory.index)

In [64]:
clean_inventory

  product_id  current_stock
0       P001             12
1       P002             15
2       P003             10
3       P004             17
5       P006              2
6       P007              6
7       P008              9
8       P009             10

In [65]:
clean_sales[~clean_sales["product_id"].isin(clean_products["product_id"])]

Empty DataFrame
Columns: [sale_id, product_id, sale_date, quantity_sold]
Index: []

In [66]:
clean_inventory[~clean_inventory["product_id"].isin(clean_products["product_id"])]

Empty DataFrame
Columns: [product_id, current_stock]
Index: []

In [67]:
clean_products[~clean_products["product_id"].isin(clean_inventory["product_id"])]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
13,P013,Wheat flour 500gm,Grocery,38.0,40.0,2.0

In [68]:
clean_products["product_id"].isnull().sum()

np.int64(0)

In [69]:
clean_products[clean_products["product_id"].duplicated()]

Empty DataFrame
Columns: [product_id, product_name, product_category, unit_price, reorder_level, lead_time_days]
Index: []

In [70]:
clean_products[clean_products["lead_time_days"]<0]

Empty DataFrame
Columns: [product_id, product_name, product_category, unit_price, reorder_level, lead_time_days]
Index: []

In [72]:
clean_sales[clean_sales["sale_id"].duplicated()]

Empty DataFrame
Columns: [sale_id, product_id, sale_date, quantity_sold]
Index: []

In [73]:
clean_sales[clean_sales["sale_id"].isnull()]

Empty DataFrame
Columns: [sale_id, product_id, sale_date, quantity_sold]
Index: []

In [74]:
clean_sales[clean_sales["quantity_sold"]<= 0]

Empty DataFrame
Columns: [sale_id, product_id, sale_date, quantity_sold]
Index: []

In [79]:
clean_inventory[clean_inventory["current_stock"]<=0]

Empty DataFrame
Columns: [product_id, current_stock]
Index: []

In [82]:
clean_products.dtypes

product_id           object
product_name         object
product_category     object
unit_price          float64
reorder_level       float64
lead_time_days      float64
dtype: object

In [83]:
clean_sales.dtypes

sale_id                  object
product_id               object
sale_date        datetime64[ns]
quantity_sold             int64
dtype: object

In [85]:
clean_inventory.dtypes

product_id       object
current_stock     int64
dtype: object

In [86]:
clean_products["reorder_level"] = clean_products["reorder_level"].astype(int)

In [87]:
clean_products["lead_time_days"] = clean_products["lead_time_days"].astype(int)

In [88]:
clean_products.dtypes

product_id           object
product_name         object
product_category     object
unit_price          float64
reorder_level         int64
lead_time_days        int64
dtype: object

In [94]:
clean_products.to_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/processed/products_clean.csv",index = False)

In [95]:
clean_sales.to_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/processed/sales_clean.csv",index = False)

In [96]:
clean_inventory.to_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/processed/inventorys_clean.csv",index = False)

In [97]:
import os

os.listdir("../data/processed")

['inventorys_clean.csv', 'products_clean.csv', 'sales_clean.csv']