In [1]:
import pandas as pd

In [2]:
###Reading the csv file
bad_products = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample bad/Products.csv")

In [6]:
bad_products.columns

Index(['product_id ', 'product_name ', 'product_category ', 'unit_price ',
       'reorder_level ', 'lead_time_days '],
      dtype='object')

In [7]:
###Cleaning rows with end white space
bad_products.columns = bad_products.columns.str.strip()

In [8]:
bad_products.columns

Index(['product_id', 'product_name', 'product_category', 'unit_price',
       'reorder_level', 'lead_time_days'],
      dtype='object')

In [26]:
###checking duplicates
bad_products[bad_products['product_id'].duplicated(keep = False)]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
8,P009,3Broom stick,Household,850.0,10.0,0.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0
10,P009,3Broom stick,Household,850.0,10.0,0.0
11,P009,3Broom stick,Household,850.0,10.0,0.0

In [19]:
###Missing product ID's
bad_products[bad_products['product_id'].isnull()]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0
12,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
###Null values in Products name
bad_products[bad_products['product_name'].isnull()]

Empty DataFrame
Columns: [product_id, product_name, product_category, unit_price, reorder_level, lead_time_days]
Index: []

In [22]:
###To check if all rows are NULL
bad_products.isnull().all(axis = 1).sum()

np.int64(1)

In [23]:
###to drop a Row with all null values in a table
bad_products = bad_products.dropna(how="all")

In [24]:
###To check if all rows are NULL
bad_products.isnull().all(axis = 1).sum()

np.int64(0)

In [27]:
###checking duplicates
bad_products[bad_products['product_id'].duplicated(keep = False)]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
8,P009,3Broom stick,Household,850.0,10.0,0.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0
10,P009,3Broom stick,Household,850.0,10.0,0.0
11,P009,3Broom stick,Household,850.0,10.0,0.0

In [28]:
###check for exact duplicates
bad_products[bad_products['product_id']=="P009"].duplicated()

8     False
10     True
11     True
dtype: bool

In [29]:
###Drop duplicates
bad_products = bad_products.drop_duplicates()

In [30]:
###checking duplicates
bad_products[bad_products['product_id'].duplicated(keep = False)]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0

In [31]:
###check for exact duplicates
bad_products[bad_products['product_id']=="P009"].duplicated()

8    False
dtype: bool

In [32]:
bad_products.isnull().sum()

product_id          2
product_name        0
product_category    0
unit_price          0
reorder_level       0
lead_time_days      0
dtype: int64

In [33]:
bad_products[bad_products["product_id"] == "P009"]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
8,P009,3Broom stick,Household,850.0,10.0,0.0

In [34]:
bad_products[bad_products["product_id"] == "P009"].duplicated()

8    False
dtype: bool

In [35]:
bad_products

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
0,P001,USB cable,Electronics,666.0,30.0,4.0
1,P002,Headphones,Electronics,932.0,25.0,6.0
2,P003,Mouse,Electronics,0.0,20.0,7.0
3,P004,Rice 10Kg,Grocery,579.0,28.0,3.0
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
5,P006,Wheat flour 500gm,Grocery,38.0,40.0,2.0
6,P007,Bucket combo,Household,486.0,20.0,4.0
7,P008,Home Cleaner,Household,520.0,15.0,3.0
8,P009,3Broom stick,Household,850.0,10.0,0.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0
13,P013,Wheat flour 500gm,Grocery,38.0,40.0,2.0

In [36]:
bad_products[bad_products["unit_price"] < 0]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0

In [37]:
###separate invalid record
invalid_record = bad_products[bad_products["unit_price"] < 0]

In [38]:
invalid_record

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0

In [40]:
bad_products[bad_products["product_id"].isnull()][["product_id","product_name","unit_price"]]

  product_id   product_name  unit_price
4        NaN    Sugar 500gm       -36.0
9        NaN  Snickers 50gm       -45.0

In [41]:
bad_products.isnull().sum()

product_id          2
product_name        0
product_category    0
unit_price          0
reorder_level       0
lead_time_days      0
dtype: int64

In [42]:
bad_products[bad_products["reorder_level"] < 0]

Empty DataFrame
Columns: [product_id, product_name, product_category, unit_price, reorder_level, lead_time_days]
Index: []

In [45]:
bad_products[bad_products["lead_time_days"] < 0]

Empty DataFrame
Columns: [product_id, product_name, product_category, unit_price, reorder_level, lead_time_days]
Index: []

In [46]:
bad_products.dtypes

product_id           object
product_name         object
product_category     object
unit_price          float64
reorder_level       float64
lead_time_days      float64
dtype: object

In [47]:
###Reading the csv file
bad_sales = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample bad/Sales.csv")

In [48]:
bad_sales.head()

  sale_id  product_id            sale_date   quantity_sold
0     S001        P005  2026-09-05 17:32:15               1
1     S002        P005  2026-09-05 17:40:09               2
2     S003        P003  2026-09-05 17:53:48               1
3     S004        P004  2026-09-05 18:12:06               1
4     S005        P001  2026-09-05 18:40:03               1

In [49]:
bad_sales.columns

Index(['sale_id ', 'product_id ', 'sale_date ', 'quantity_sold '], dtype='object')

In [50]:
bad_sales.columns = bad_sales.columns.str.strip()

In [51]:
bad_sales.columns

Index(['sale_id', 'product_id', 'sale_date', 'quantity_sold'], dtype='object')

In [52]:
bad_sales.isnull().sum()

sale_id          0
product_id       0
sale_date        0
quantity_sold    0
dtype: int64

In [54]:
bad_sales.duplicated().sum()

np.int64(0)

In [56]:
bad_sales["sale_id"].isnull().sum()

np.int64(0)

In [57]:
bad_sales["sale_id"].duplicated().sum()

np.int64(0)

In [58]:
bad_sales[~bad_sales["product_id"].isin(bad_products["product_id"])]

   sale_id product_id            sale_date  quantity_sold
0     S001       P005  2026-09-05 17:32:15              1
1     S002       P005  2026-09-05 17:40:09              2
17    S018       P010  2026-09-07 22:40:09              4
22    S023       P010  2026-09-08 23:51:01              2
24    S025       P010  2026-09-09 10:53:48              3
27    S028       P005  2026-09-09 11:48:27              2

In [60]:
bad_products[bad_products["product_id"].isin(["P005","P010"])]

Empty DataFrame
Columns: [product_id, product_name, product_category, unit_price, reorder_level, lead_time_days]
Index: []

In [61]:
invalid_sales = bad_sales[~bad_sales["product_id"].isin(bad_products["product_id"])]

In [62]:
invalid_sales

   sale_id product_id            sale_date  quantity_sold
0     S001       P005  2026-09-05 17:32:15              1
1     S002       P005  2026-09-05 17:40:09              2
17    S018       P010  2026-09-07 22:40:09              4
22    S023       P010  2026-09-08 23:51:01              2
24    S025       P010  2026-09-09 10:53:48              3
27    S028       P005  2026-09-09 11:48:27              2

In [63]:
bad_sales["sale_date"] = pd.to_datetime(bad_sales["sale_date"],errors="coerce")

In [66]:
invalid_sale_dates = bad_sales[bad_sales["sale_date"].isnull()]

In [67]:
invalid_sale_dates

Empty DataFrame
Columns: [sale_id, product_id, sale_date, quantity_sold]
Index: []

In [69]:
bad_sales[bad_sales["quantity_sold"] <= 0]

Empty DataFrame
Columns: [sale_id, product_id, sale_date, quantity_sold]
Index: []